//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blud_and_nap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blud_and_nap()
        {
            this.Rezepts = new HashSet<Rezepts>();
            this.Sost_zakaz = new HashSet<Sost_zakaz>();
        }
    
        public int ID_Blud_and_nap { get; set; }
        public int ID_Categ { get; set; }
        public string Foto { get; set; }
        public string Name { get; set; }
        public int Cena { get; set; }
        public bool Block { get; set; }
    
        public virtual Categ Categ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezepts> Rezepts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sost_zakaz> Sost_zakaz { get; set; }
    }
}
