//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingred
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingred()
        {
            this.Jurn_ychet_ingred = new HashSet<Jurn_ychet_ingred>();
            this.Sost_rez = new HashSet<Sost_rez>();
        }
    
        public int ID_Ingred { get; set; }
        public string Name { get; set; }
        public int Ves { get; set; }
        public int ID_Ed_izm { get; set; }
        public int Pred_sroc_hran { get; set; }
    
        public virtual Ed_izm Ed_izm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jurn_ychet_ingred> Jurn_ychet_ingred { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sost_rez> Sost_rez { get; set; }
    }
}
