//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurn_ychet_ingred
    {
        public int ID_Jurn_ingred { get; set; }
        public int ID_Ingred { get; set; }
        public int ID_Type_ychet { get; set; }
        public System.DateTime Date_oper { get; set; }
        public int Kol { get; set; }
        public double Ves { get; set; }
    
        public virtual Ingred Ingred { get; set; }
        public virtual Type_ychet Type_ychet { get; set; }
    }
}
