//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sost_zakaz
    {
        public int ID_Sost_zakaz { get; set; }
        public int ID_Zakaz { get; set; }
        public int ID_Blud_and_nap { get; set; }
        public string Komment { get; set; }
    
        public virtual Blud_and_nap Blud_and_nap { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
