//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sost_rez
    {
        public int ID_Sost_rez { get; set; }
        public int ID_Rezept { get; set; }
        public int ID_Ingred { get; set; }
        public Nullable<int> Kol { get; set; }
        public Nullable<double> Ves { get; set; }
    
        public virtual Ingred Ingred { get; set; }
        public virtual Rezepts Rezepts { get; set; }
    }
}
