//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.Sost_zakaz = new HashSet<Sost_zakaz>();
        }
    
        public int ID_Zakaz { get; set; }
        public int ID_User { get; set; }
        public bool Sost_gotov { get; set; }
        public int Ob_stoim { get; set; }
        public bool Oplacheno { get; set; }
        public Nullable<System.DateTime> Date_zakaz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sost_zakaz> Sost_zakaz { get; set; }
        public virtual User User { get; set; }
    }
}
